- hosts: centos
  become: yes
  tasks:
    
    - name: install apache2
      yum:
        name: httpd
        state: present

    - name: start apache2 
      service:
        name: httpd
        state: started

    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/
      notify: restart httpd

    - name: create a file
      file:
        path: /home/ansadm/xzy1
        state: touch
      register: output


  handlers:
    - name: restart httpd
      service: 
        name: httpd
        state: restarted
