- hosts: centos
  become: yes
  ignore_errors: yes
  tasks:
    
    - name: install apache2
      yum:
        name: httpd
        state: present
      tags: install

    - name: create a file
      file:
        path: /home/ansadm/xzy1
        state: directory
      register: output
      tags: dir

    - name: start apache2 
      service:
        name: httpd
        state: started
      tags: start

    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/
      notify: restart httpd
      


  handlers:
    - name: restart httpd
      service: 
        name: httpd
        state: restarted
