---

- hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    
    - name: creating user
      user:
        name: "{{uname}}"
        uid: "{{uuid}}"
        home: "{{uhome}}"
        shell: "{{ushell}}"
