---
# tasks file for web

- name: install mysql-server
  apt:
    name: "{{item}}"
    state: present
  with_items:
      - "{{mysql}}"
      - python
      - python-mysqldb

- name: start mysql service
  service:
    name: mysql
    state: started

- name: copy index.html file
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: creating accounts database
  mysql_db:
    name: accounts
    state: present

- name: creating mysql user
  mysql_user:
    name: admin
    password: admin
    priv: '*.*:ALL'
    host: '%' 
    state: present
- name: change the port of web server
  copy:
    src: ports.conf
    dest: /etc/apache2/ports.conf
  notify: restart
- name: copy mysql-conf files
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart 

